### ISSUE TITLE
Order total = 0 (helpscout ticket)

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#10]
This error happens when the total ends up with 0kr (or less then 6kr?).

The product has a price but the seller wants to be able to give away a discount code and free shipping so the product is "free" = 0 kr. 

Fatal error: Uncaught PaysonEmbedded\PaysonApiException: Api errors Message: HTTP status code: 400, Model validation failed. Parameter: Message: 'Total Price Including Tax' must be greater than or equal to '6'. Parameter: Order.TotalPriceIncludingTax in /home/www/victura.nu/wp-content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/lib/paysonapi.php:125 Stack trace: #0 /home/www/victura.nu/wp-content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/lib/paysonapi.php(65): PaysonEmbedded\PaysonApi->doCurlRequest('PUT', 'https://api.pay...', Array) #1 /home/www/victura.nu/wp-content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/class-wc-paysoncheckout-setup-payson-api.php(69): PaysonEmbedded\PaysonApi->UpdateCheckout(Object(PaysonEmbedded\Checkout)) #2 /home/www/victura.nu/wp-content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/class-wc-paysoncheckout-ajax-handler.php(35): WC_PaysonCheckout_Setup_Payson_API->get_checkout(421) #3 /home/www/victura.nu/wp-includes/plu in /home/www/victura.nu/wp-content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/lib/paysonapi.php on line 125

**Comment by slobodan** [comment]
@boozebrorsan, doesn't seem like something we will be able to fix, if Payson's API requires price of at least 6 kr. But leaving the issue open until I confirm.
