### ISSUE TITLE
Check for "EnabledForInvoice" to alert users that they don't have Invoice set in their account at Payson

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#13]
_Det finns i API:et ett anrop till ”Accounts”, som returnerar info om användaren och som kommer returnera ”EnabledForInvoice” true/false beroende på om det är aktiverat.
 
Anropet kan ju bara göras med korrekt API-nyckel för butiken, men du skulle alltså kunna lägga till någon ”Verify credentials”-knapp eller liknande i samband med att kunderna anger sina api-credentials
 
https://api.payson.se/wp/new-api/api-methods/validate/_

**Comment by MichaelBengtsson** [comment]
Should be fixed
