### ISSUE TITLE
Fail with a deposit method

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/paysoncheckout-for-woocommerce#19]
From Michael at Payson:

Our mutual customer, www.nevincosmetics.com, is experiencing some problems and I have been trying to see what is going on.
 
If you fail with a  deposit method, we redirect the customer back to the checkoutUri, “https://www.nevincosmetics.com/kassan/”  in this case.
 
When this page is loaded, the shop tries to do a PUT and update the checkout, And in this PUT the itemId is missing from the orderItems. This means our api interprets the call as an attempt to remove all old items, and create new items.
 
After the customer has tried to make an deposit though, we no longer allow orderItems to be updated and the PUT api-call returns an error message. This in turn leads to that the customers call to the checkoutUri ends with an 500 error code trying to call https://www.nevincosmetics.com/wp-admin/admin-ajax.php with action “wc_paysoncheckout_iframe”.
 
So, could you please look into the issue of itemId’s not being present when you do puts. And also, why is an PUT necessary for when the customer is trying to load the checkout?
 
The put made to our api. Notice itemId being null:
 
![image004](https://cloud.githubusercontent.com/assets/985946/21988265/f12af26c-dc06-11e6-9dbe-224f00029566.png)

**Comment by cesrafa** [comment]
I think I was having this same issue, but when I simulated a "credit card denial" in test mode. Was this fixed on version 1.1?

**Comment by MichaelBengtsson** [comment]
Should be fixed
