### ISSUE TITLE
The use of WooCommerce shipping classes with different zip codes

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#20]
We are using different shipping classes in WooCommerce that is connected to different zip-codes.
The shipping option "Hide shipping cost until the address has been added" is active.
Now it doesnt work any longer, this worked on Payson 1.0 but doesnt work with 2.0.

Does the 2.0 has the function to calculate the shipping when zip codes is inserted?
Is it possible to add support for this?

**Comment by MichaelBengtsson** [comment]
Should be fixed
