### ISSUE TITLE
Fatal Error when Payson 2.0 is active and WooCommerce is deactivated.

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#21]
The client got this problem when WC was updated from 2.6.13 to 2.6.14:

Fatal error: Class 'WC_Payment_Gateway' not found in /home/mannabies/public_html/content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/gateways/class-wc-paysoncheckout-gateway.php on line 23

It looks like if you deactive WooCommerce and Payson 2.0 is still activated it will show this error.

**Comment by MichaelBengtsson** [comment]
Should be fixed.
