### ISSUE TITLE
Phonenumber is not seen on the order in Payson Admin

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#24]
It looks like the phonenumber in the WC order is not added to the order in Payson Admin.

**Comment by NiklasHogefjord** [comment]
I've checked this and can confirm that if a phone number exist in the returned customer data our plugin is adding it to the order. But in some cases the phone number seems to be missing, even though the requestPhone setting is enabled in our payment gateway settings. I have sent Payson a ticket about this.

**Comment by MichaelBengtsson** [comment]
Not an issue on our end.
