### ISSUE TITLE
Division by zero in some cases

### ISSUE THREAD

**Issue by ImadBazzal** [krokedil/paysoncheckout-for-woocommerce#31]
https://github.com/krokedil/paysoncheckout-for-woocommerce/blob/85112c43887aa64738e769dd6bbe1a513e1e7c23/includes/class-wc-paysoncheckout-process-order-lines.php#L278

Also, it would be great if You add filters to shipping name, taxes and reference.

Sincerely, Imad Bazzal.

**Comment by MichaelBengtsson** [comment]
Adressed in eb97a9f8f5f339ac58b197caa99c5f8a951d3c0a
