### ISSUE TITLE
Iframe halts in pause/load state when proceeding to finalize purchase (Slutför köp)

### ISSUE THREAD

**Issue by jnystromdesign** [krokedil/paysoncheckout-for-woocommerce#37]
After adding personal number, post code, name and phone number the iframe reloads and shows the fetched personal data and "finalize purchase" button is visible, under an overlay with a load spinner, and is stuck in that state. 
If I refresh the page the spinner and its overlay disappears. 

The log only shows updated item: 
`10-27-2017 @ 11:19:27 - Update local order. Order ID: 3563`

and from the console a Internal server error (500) from wp-admin/amin-ajax.php is shown: 
```
Address update AJAX error paysoncheckout.js?ver=1.1.10:157 
{errror object} paysoncheckout.js?ver=1.1.10:162 
Address update AJAX complete paysoncheckout.js?ver=1.1.10:162
```

Using *Wordpress 4.6.7* and *WooCommerce 2.6.4*

**Comment by MichaelBengtsson** [comment]
Should be fixed with e251a2fde0026b6a628600e12c7671703c37fbee
