### ISSUE TITLE
Payson 2.0 does not work with WooCommerce Product Add-Ons

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/paysoncheckout-for-woocommerce#38]
Add-On information does not get saved on the order being made.

**Comment by tomaswilhelmsson** [comment]
Having same problem :/

**Comment by tomaswilhelmsson** [comment]
Any update on this? :/ this is a major issue for us users :/

**Comment by NiklasHogefjord** [comment]
Sorry for the late reply. I've tested it and it works now (tested with version 1.3.0). 

The change in how the WC checkout form is processed when customer finalize the purchase in Paysons checkout in the 1.2.0 release (https://github.com/krokedil/paysoncheckout-for-woocommerce/releases/tag/1.2.0) should have solved this issue.
