### ISSUE TITLE
Pay with another payment function way has stopped working

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#42]
The error appears when you are in the checkout and try and change to a different payment way using the built in button. It takes you to the regular checkout but within a few seconds it jumps back to the paysoncheckout again.

I got the same error on our demo-site: https://demo.krokedil.se/paysoncheckout2/

**Comment by NiklasHogefjord** [comment]
Fixed in 422ae2f5289f1d2f67ead07d9be7508da26277bd. Available in version 1.1.14 here https://wordpress.org/plugins/krokedil-paysoncheckout-20-for-woocommerce/ and here https://github.com/krokedil/paysoncheckout-for-woocommerce/releases/tag/1.1.14.
