### ISSUE TITLE
Pay with another paymentway - issue after last fix

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/paysoncheckout-for-woocommerce#43]
1. When you choose to pay with another way in the checkout. 
2. Then start to fill in your credentials. Tab yourself through the forms.
3. When you reach "zip-code" and has filled in the zip-code number the cart refresh and you are back in the Payson Checkout again.

**Comment by NiklasHogefjord** [comment]
Fixed in https://github.com/krokedil/paysoncheckout-for-woocommerce/releases/tag/1.2.0
