### ISSUE TITLE
Order notes are not saved

### ISSUE THREAD

**Issue by cesrafa** [krokedil/paysoncheckout-for-woocommerce#45]
Hi, 
I noticed that everytime I make a test purchase and write something on order notes, with the same user, I get the message for the last order.

For example: If I pay order A, with note A, and then check the order notes on admin dashboard, I get nothing. Then, if I pay order B, with note B, then I get the text from note A (instead of B). 

I cheked the code and I think it has to do with this:

`WC()->session->save( 'payson_customer_order_note' )` 

It seems it saves the information to the current session, but by the time it is saved, the order is already created/saved, so this information won't be updated until the next purchase/order (as long as it is the same user).

This happened to me with version 1.14.0 on Firefox/chrome. I tried to use v1.2.0 but I got many errors there and my checkout did not work at all.

**Comment by NiklasHogefjord** [comment]
Sorry for the late reply. Will look into this.
