### ISSUE TITLE
Remove PHP notices and deprecated messages

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/paysoncheckout-for-woocommerce#50]

**Comment by NiklasHogefjord** [comment]
Notice: Undefined index: section in /xyz/wp-content/plugins/krokedil-paysoncheckout-20-for-woocommerce/includes/class-wc-paysoncheckout-admin-notices.php on line 57

**Comment by MichaelBengtsson** [comment]
Fixed in version 2.0.0. Closed

**Comment by baseloo** [comment]
Backup to appear in 2.0.1
