### ISSUE TITLE
Fix deprecated messages for cart taxes

### ISSUE THREAD

**Issue by jonasostrom** [krokedil/paysoncheckout-for-woocommerce#56]
Hi,

Is it possible to fix deprecated code on line 220 in class-wc-paysoncheckout-wc-order.php
Change foreach loop to:

`foreach ( array_keys( WC()->cart->get_cart_contents_taxes() + WC()->cart->get_shipping_taxes() ) as $tax_rate_id )`

This will get rid of some deprecated messages.

**Comment by Kristian-Andersson** [comment]
Hi,

We are currently working on a rewrite for Payson Checkout where this notice will be fixed and removed.

**Comment by MichaelBengtsson** [comment]
Fixed with version 2.0.0. Closed
