### ISSUE TITLE
Session error when updating cart and navigating back to checkout

### ISSUE THREAD

**Issue by Kristian-Andersson** [krokedil/paysoncheckout-for-woocommerce#79]
Following steps will cause: "400 Bad Request - The property can't
be updated." error.
1. Go to checkout and proceed to Payson
2. "Simulate Deny" on test environment (equivalent to cancel on real
banking) and return to the shop
3. Change the cart contents
4. Try to proceed to the checkout once more.

**Comment by Kristian-Andersson** [comment]
We're getting 400 bad request as response of update request.

**Comment by MichaelBengtsson** [comment]
This should be solved now
