### ISSUE TITLE
Implement frontend validation

### ISSUE THREAD

**Issue by Kristian-Andersson** [krokedil/paysoncheckout-for-woocommerce#86]
Waiting for Payson to implementing this functionality. This implementation will allow us to create the order according to WooCommerce's order creation flow, increasing the compatibility for other plugins.

**Comment by Kristian-Andersson** [comment]
Plugin: WooCommerce Order Delivery is not compatible with Payson Checkout 2.0 due to the current checkout flow.

**Comment by MichaelBengtsson** [comment]
Closing this since its been done
